name: EC2Deployment

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]


jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        if: ${{ success() }}
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
